<h1 style="font-family: cursive; font-size: 80px; color:blue;">Index</h1>
<br><br>

- Walrus operator
- Lexicographically Comparsion
- Operator Precedence
- List 
- Numpy array
- Function as Object
- Exception
    - Raise
    - Assert
- File handling
- Data Type
- Dictionary
- Tuple



# Walrus operator
- Take input in different way

In [3]:
# Old way
num=int(input("Enter the number "))
print(num)

Enter the number 3
3


In [4]:
# New way
print(num:=int(input("Enter the number ")))

Enter the number 3
3


# Lexicographically Comparsion
- Compare the words in alphabetic order
- A is smaller than B
- a is greater then A
- If the first letter is same then it will check the next letter and so on.

In [5]:
print("A"<"B")

True


In [11]:
print('a'>'A')

True


In [12]:
print("Monis">"Muin")

False


### Q )

In [13]:
if (1==1) and (2+2>3):
    print(True)
else:
    print(False)

True


# Operator Precedence
- Like, Muliplication is perform before Addition.

In [14]:
print(False == False or True)

True


In [15]:
print(False==(False or True))

False


In [16]:
print((False == False) or True)

True


### Q )

In [17]:
if 1+1*3==6:
    print("Yes")
else:
    print("No")

No


### Q ) 

In [18]:
x=4
y=2
if not 1+1==y or x==4 and 7==8:
    print(True)
elif x>y:
    print(False)

False


# List

In [21]:
x=3
h=['string',0,[1,2,x],2]

In [24]:
h[1],h[0],h[2],h[2][2]

(0, 'string', [1, 2, 3], 3)

In [25]:
l=[7,7,7,7]
l[1]=3
l

[7, 3, 7, 7]

###  Q )

In [27]:
num=[10,9,8,7,6,5]
num[0]=num[1]-5
if 4  in num:
    print(num[3])
else:
    print(num[4])

7


# Numpy array
- Array is collection same data_type

In [29]:
import numpy as np
a=np.arange(5)
print(a)

[0 1 2 3 4]


In [33]:
a1=np.array([1,2,3],dtype='float64')
print(a1)

[1. 2. 3.]


Hence Array is collection of same dtype, so it will convert all data into string form.

In [43]:
a2=np.array([1,'monis',1.2])
a2

array(['1', 'monis', '1.2'], dtype='<U32')

In [45]:
a3=np.array([1,2.3,4.5],dtype=np.int32)
a3

array([1, 2, 4])

# Function as Object

In [46]:
# Old way

def mul(x,y):
    return x*y
mul(2,3)

6

- The Example below assign the function `mul` to a variable `operation`
-  Now the name ` operation ` can also be use to call function

In [47]:
# New way

def mul(a,b):
    return a*b

operation=mul
operation(3,4)

12

###  Function can also used as argument of other function.

In [49]:
def add(x,y):
    return x+y
def do(fun,x,y):
    return fun(fun(x,y),fun(x,y))

a=5
b=10

do(add,a,b)

30

# Exceptions
- It is an Run time error.
- Types of Error :-
    - import Error
    - index Error
    - name Error
    - Syntax Error
    - Type Error
    - Value Error

There are 3 type of block, that used in exception handling
- Try
- Except
- finally

Explaination:- 

* TRY block is used to monitor the code that may/may not be throw an error.
* EXCEPT block is used, when exception occure then it will execute.
* FINALLY block is used, Exception occure or not it still execute.

In [55]:
try:
    print(7/2)
except ZeroDivisionError as e :
    print(e, "\nYou can't divide a number by zero")
finally:
    print("Thanks")

3.5
Thanks


In [54]:
try:
    print(7/0)
except ZeroDivisionError as e :
    print(e, "\nYou can't divide a number by zero")
finally:
    print("Thanks")

division by zero 
You can't divide a number by zero
Thanks


We can use multiple `except` block but only 1 `try` block

In [56]:
try:
    v=3
    print(v+"hello")
    print(v/2)
except ZeroDivisionError:
    print("Cannot divide by zero")
except (ValueError, TypeError):
    print("Alert,  Error!!")

Alert,  Error!!


An ` Except ` statement without any exception specification will catch all Errors.

In [64]:
try:
    print(7/3)
    print(3+'add')
except :
    print("Error!!!")

2.3333333333333335
Error!!!


## Raise Error

If we don't specify the type, it will be ` Run time Error `.

In [65]:
print(3)
raise
print(4)

3


RuntimeError: No active exception to reraise

With type specification

In [66]:
print(2)
raise ValueError
print(4)

2


ValueError: 

With Type and Message Specification.

In [69]:
print(3)
raise TypeError(' You cannot write 3 according to monis ')
print(5)

3


TypeError:  You cannot write 3 according to monis 

## Assertions
- It is like conditional satament.

In [70]:
try:
    print(0)
    assert 2==2
    print(1)
except:
    print(3)

0
1


In [74]:
print(0)
assert 2==3
print(1)
   

0


AssertionError: 

In [75]:
try:
    print(0)
    assert 2==3
    print(2)
except:
    print(3)

0
3


# File Handling


| Mode | Function |
| -------| ---------| 
| w | For Writing in File |
| r | For Reading from File |
| a | For Adding in File |
| b | It is used for non-text file,like image or sounds |

- After opening of File, we have to make sure to Close it.

In [80]:
f=open("file",'r')
print(f)
f.close()

<_io.TextIOWrapper name='file' mode='r' encoding='cp1252'>


##  Reading File

In [82]:
f=open("file1",'r')
c=f.read()
print(c)
f.close()

Hey I am monis Monis
I am going to be a great programmer in this world as ever know!
and i am kind of introvert person. 


In [84]:
f=open('file1','r')
print(f.read(13))
print(f.read(3))
print(f.read())
f.close()

Hey I am moni
s M
onis
I am going to be a great programmer in this world as ever know!
and i am kind of introvert person. 


#### readline() Method-
- To read an line from file

In [86]:
f=open('file1','r')
print(f.readline())
f.close()

Hey I am monis Monis



#### We can use Loop also.

In [90]:
f=open('file1','r')
for i in f:
    print(i)

Hey I am monis Monis

I am going to be a great programmer in this world as ever know!

and i am kind of introvert person. 


## Write File 
- It will create a file, if it does not already exsist.
- If file exsist, then i will erase all data and new data is get written.
- If we have to persevere previous data, then we have to use `a i.e append mode `.
- If we open file in write mode and immediately close, then the file contents are deleted.

In [91]:
f=open("newfile",'w')
f.write("This is what is going to get written in File")
f.close()

In [92]:
f=open('newfile','r')
f.read()

'This is what is going to get written in File'

To count the letter we have written


In [93]:
msg="Hello world"
f=open('newfile10','w')
count=f.write(msg)
print(count)
f.close()

11


In [96]:
f=open('newfile10','r')
print(f.read())
f.close()

Hello world


**Good Way of File Handling**
- It make sure file get closed.

In [97]:
try:
    f=open('file1','r')
    print(f.read(10))
finally:
    f.close

Hey I am m


### Alternative way of File handling
- By using ` with ` and ` as ` statement.
- This will close file automatically

In [98]:
with open('file1','r') as f:
    print(f.read())

Hey I am monis Monis
I am going to be a great programmer in this world as ever know!
and i am kind of introvert person. 


# Data Type

In [100]:
a=2.5
b=2
type(a),type(b)

(float, int)

In [110]:
s='Monis'
type(s)

str

In [108]:
# Here we can used only "J" varibale
x=2+3j
print(x)
print(type(x))

(2+3j)
<class 'complex'>


In [109]:
a=3
b=4
print(complex(a,b))

(3+4j)


# Dictionary

In [111]:
d={1:'monis',2:'muin',3:'jishan_bhaiya'}
print(d)

{1: 'monis', 2: 'muin', 3: 'jishan_bhaiya'}


To add in dictionary

In [113]:
d[4]="Asad"
print(d)

{1: 'monis', 2: 'muin', 3: 'jishan_bhaiya', 4: 'Asad'}


To form dict from 2 list


In [123]:
k=["monis","muin"]
v=[21,43]
m=dict(zip(k,v))
m

{'monis': 21, 'muin': 43}

In [115]:
m['monis']

21

In [117]:
m.keys()

dict_keys(['monis', 'muin'])

In [118]:
m.values()

dict_values([21, 43])

In [119]:
m.items()

dict_items([('monis', 21), ('muin', 43)])

To remove an Element, we use `del` or `pop`

In [124]:
del m['muin']
m

{'monis': 21}

In [127]:
m.pop('monis')
m

{}

In [128]:
d

{1: 'monis', 2: 'muin', 3: 'jishan_bhaiya', 4: 'Asad'}

To delete all, we can use `clear`.

In [129]:
d.clear()
d

{}

We can use 1 key and Value have more dictionary

In [130]:
d={1:'monis',2:{1:'one',2:'two'},3:'Muin'}
d

{1: 'monis', 2: {1: 'one', 2: 'two'}, 3: 'Muin'}

In [131]:
d[1]

'monis'

In [132]:
d[2]

{1: 'one', 2: 'two'}

In [133]:
d[2][1]

'one'

We can use get method, If value is present then we get Value or if not then we did't get an Error

In [136]:
d

{1: 'monis', 2: {1: 'one', 2: 'two'}, 3: 'Muin'}

In [135]:
d[4]

KeyError: 4

In [137]:
d.get(3,'sorry')

'Muin'

In [139]:
d.get(4,'sorry')

'sorry'

In [140]:
d.get(4) #Nothing happend even i run the code.

# Tuple
- immutable
- Trying to reassign a value will cause an TypeError

In [141]:
x=(1,2,3,4)
x

(1, 2, 3, 4)

In [142]:
x[2]

3

In [143]:
x[1]=2

TypeError: 'tuple' object does not support item assignment

Tuple can be created without parenthesis.

In [144]:
x=1,2,3,4
x

(1, 2, 3, 4)

Tuple unpacking

In [147]:
x=(1,2,3,4,5)
a,*b,c=x

In [148]:
a

1

In [151]:
b # It form a List

[2, 3, 4]

In [153]:
b[0]=10
b

[10, 3, 4]

In [152]:
c

5